### ISSUE TITLE
EN section is blank when editing a word

### ISSUE THREAD

**Issue by bluebear94** [Ziphil/ZpdicShaleian#1]
When opening the dialog to edit a word, the EN section is blank in the window.

To reproduce:

1. Add a word and put something in the EN section
2. Save and reload the file
3. Double-click on the new word to open the edit dialog

Expected behavior: The contents of the EN section that I put previously should be there when editing the word.

Actual behavior: The EN section is blank in the edit dialog.

**Comment by Ziphil** [comment]
Thank you for reporting. I also noticed this issue and fixed it in 5ac54b4c40f99a64f74e2d05146a6207f46bc1b5.
