### ISSUE TITLE
辞書を開いていないときの「単語の新規作成」

### ISSUE THREAD

**Issue by shwaka** [Ziphil/ZpdicShaleian#3]
辞書を開いていないとき(ソフトウェアをダウンロードした直後)に「単語の新規作成」をした際の挙動が怪しいです．

## Expected behavior
単語の作成ができないのは正しい挙動である(という認識は正しいですか？)
その上で，以下のいずれか挙動をするのが望ましい．

- 辞書を開いていない状態では，そもそも「単語の新規作成」を選択できない．
- 「先に辞書を開いてください」などのエラーメッセージを表示する．

## Current behavior
「単語の新規作成」を選択することができるが，何の反応もない．(単語作成画面が出るわけでもエラーメッセージが表示されるわけでもない)

**Comment by Ziphil** [comment]
辞書を開いていないときに様々な操作で何も反応がないのは意図通りです (処理をサボっているだけ)。今後、「先に辞書を開いてください」というポップアップを表示するようにする予定です。
